### PR TITLE
Fix `$start` use problem on `getCalList()`

### PR DESCRIPTION
**Pull request by lherry**
There was a problem with `getCalList()` when `$start != 1`...

### CODE REVIEW

**Comment by lherry** [comment]
The pull request includes the update of french messages definitions

**Comment by lherry** [comment]
Yes you are right, but if you try to use your `dayList()` method with `$start = 2`, we will have days in bad order... no ?

**Comment by kartik-v** [comment]
No the days will start from Monday if you set start to 2. Check the example again.

**Comment by lherry** [comment]
Yes it starts by Monday, but after we have Sunday and next Saturday... which is reversed, no ?

**Comment by kartik-v** [comment]
Check the [example for `dayList` in the demo](http://demos.krajee.com/helper-functions/enum#dayList) and see if you can test and understand.

**Comment by lherry** [comment]
Ok, but I've got an Error (#1) : An internal server error occurred.

**Comment by kartik-v** [comment]
Refresh the page and try.

**Comment by lherry** [comment]
Result of your given test : 
```php
print_r(Enum::dayList(false, 2));

Array ( [1] => Lundi [2] => Dimanche [3] => Samedi [4] => Vendredi [5] => Jeudi [6] => Mercredi [7] => Mardi )
```

I'm waiting for something like this : 
```php
Array ( [1] => Lundi [2] => Mardi [3] => Mercredi [4] => Jeudi [5] => Vendredi [6] => Samedi [7] => Dimanche )
```

**Comment by kartik-v** [comment]
You probably are using a wrong version or a different code from your side.

Cross check the demo again and the output. The following code:
```php
print_r(Enum::dayList(true, 2, 'upper'));
```
gives this output:
```
Array
(
    [1] => MON
    [2] => SUN
    [3] => SAT
    [4] => FRI
    [5] => THU
    [6] => WED
    [7] => TUE
)
```

**Comment by kartik-v** [comment]
Let me recheck on this and get back.

**Comment by kartik-v** [comment]
Thanks for the update. Merging this.

**Comment by kartik-v** [comment]
It would be good if you can complete all the French translations for benefit of others.

**Comment by lherry** [comment]
You're welcome ! Thanks to give us usefull extensions !
Of course for translating, I've done all I know but there are some words which don't need to be translated (app names, models,...), or they are equivalent from us to fr (would you like that I add the matching to show that it is explicitely translated ?)...
So I'll add plural's definitions and, to me, except if I missed something else, all is done !

**Pull request merged**
